const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(pathToFileURL(path.resolve('index.html')).href);
    await page.locator('#autoBtn').click();
    await page.locator('#results .variant').first().waitFor();
    assert.equal(await page.locator('#metricConflicts').innerText(), '0');
    assert.equal(await page.locator('#metricTime').innerText(), '01:41:12');
    assert.equal(await page.locator('.rail').count(), 12);
    const savedCounts = await page.locator('.train-fields input[type="number"]').evaluateAll(inputs => inputs.map(input => input.value));
    await page.locator('#withoutCarsBtn').click();
    assert.equal(await page.locator('#withoutCarsBtn').getAttribute('aria-pressed'), 'true');
    assert.deepEqual(await page.locator('.train-fields input[type="number"]').evaluateAll(inputs => inputs.map(input => input.value)), savedCounts);
    await page.locator('#autoBtn').click();
    await page.locator('#results .variant').first().waitFor();
    assert.equal(await page.locator('#metricTime').innerText(), '01:40:00');
    assert.equal(await page.locator('#metricConflicts').innerText(), '0');
    assert.equal(await page.locator('#comparisonWith').innerText(), '01:41:12');
    assert.equal(await page.locator('#comparisonWithout').innerText(), '01:40:00');
    assert.match(await page.locator('#results .variant').first().innerText(), /Без вагонов/);
    await page.locator('#withCarsBtn').click();
    assert.deepEqual(await page.locator('.train-fields input[type="number"]').evaluateAll(inputs => inputs.map(input => input.value)), savedCounts);
    await page.locator('#autoBtn').click();
    await page.locator('#results .variant').first().waitFor();
    assert.equal(await page.locator('#metricTime').innerText(), '01:41:12');
    await page.screenshot({ path: 'desktop.png', fullPage: true });
    await page.locator('#playBtn').click();
    await page.waitForTimeout(500);
    assert.notEqual(await page.locator('#clock').innerText(), '00:00:00');
    await page.locator('#pauseBtn').click();
    await page.locator('#results button').first().click();
    assert.equal(await page.locator('#results .variant').count(), 6);
    await page.locator('#manualBtn').click();
    assert.equal(await page.locator('#metricConflicts').innerText(), '0');
    await page.locator('#autoBtn').click();
    await page.locator('#results .variant').first().waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'mobile.png', fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.locator('#routingMode').selectOption('continuous');
    await page.locator('#autoBtn').click();
    await page.locator('#results .variant').first().waitFor();
    assert.equal(await page.locator('#metricConflicts').innerText(), '0');
    assert.equal(await page.locator('#metricStops').innerText(), '00:00:00');
    assert.equal(await page.locator('#metricTime').innerText(), '01:41:12');
    await page.locator('#withoutCarsBtn').click();
    await page.locator('#autoBtn').click();
    await page.locator('#results .variant').first().waitFor();
    assert.equal(await page.locator('#metricTime').innerText(), '01:40:00');
    assert.equal(await page.locator('#metricConflicts').innerText(), '0');
    await page.locator('#train-1-speed').fill('0');
    await page.locator('#train-1-speed').press('Tab');
    assert.match(await page.locator('#warnings').innerText(), /положительной/);
    assert.equal(await page.locator('#comparisonWith').innerText(), 'Не рассчитано');
    assert.equal(await page.locator('#comparisonWithout').innerText(), 'Не рассчитано');
    assert.deepEqual(errors, []);
    console.log('Desktop/mobile, optimization, playback, exact start reuse and invalid input checks passed.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
